Jiawei/recruitment/eventpage
NUS-Fintech-Society/Atlas_2 pull request #95
Opened 2023-06-09 18:28 UTC by Kappaccinoh

# Description

Add edit and delete functions to event page

Fixes # (issue)

Reorganised router file structure, separated attendance and event 
Pending final UI updates from Dilys for Button or Popup UI

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-06-14 16:10 UTC, woowenjun99 commented
Hi, good attempt. No worries, if you need help, feel free to reach out to Michael, me or Jess. Try to fix the merge conflicts via rebase (or merge if you are not confident) first

2023-06-15 14:21 UTC, michaelseyo commented on src/components/attendance/DataTableModal.tsx
> +  const confirmDelete = trpc.event.deleteEvent.useQuery(modal.id)
We use useQuery when we are trying to retrieve things. In the case of a deletion, it is an example of a mutation as we are changing something, so here we will be using `useMutation` instead. You can refer to the other examples of useMutation existing in our code base and how it is written and also read up on some documentation.

2023-06-15 14:23 UTC, michaelseyo commented on src/components/attendance/DataTableModal.tsx
> +  // const confirmDelete = async() => {
how come this is commented out? You're going on the right track here using `mutateAsync` , but it'll require an input that you are passing in to know which event you are deleting. Along with the comment above, you could deconstruct what is returned by useMutation by doing `const { mutateAsync } = ... ` in order to get `mutateAsync` function.

2023-06-15 14:32 UTC, michaelseyo commented on src/server/trpc/router/event/deleteEvent.ts
> +    .query(async ({ input }) => {
Likewise, deleting an event is a `mutation` so you should be using `mutation` here instead of a `query`

2023-06-15 14:44 UTC, michaelseyo requested changes
some changes required

2023-06-16 05:17 UTC, Kappaccinoh commented
Hi @michaelseyo and @woowenjun99 I have made the changes and resolved the conflicts, hope the PR is fine this time. Thanks.

2023-06-19 01:28 UTC, michaelseyo commented on src/server/trpc/router/event/updateEvent.ts
> +                title: 'Create event failed',
Update event

2023-06-19 01:30 UTC, michaelseyo reviewed
Just a small change to be made but other than that looks good, try and do `yarn run build` to see if you're able to build.

2023-06-19 03:29 UTC, Kappaccinoh commented
okay should be good @michaelseyo

2023-06-28 16:24 UTC, michaelseyo approved these changes

2023-06-28 16:24 UTC, merged